### ISSUE TITLE
Update discord.py dependency to 1.3.4

### ISSUE THREAD

**Issue by naschorr** [naschorr/hawking#59]
I've been noticing that Hawking (and Clipster) will seem to come online and offline more often than they should. After taking a look at the logs, I've noticed that there are some instances of the socket closing, and the service having to reconnect it automatically. `websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason`. Upon further inspection, there is a constant type error that seems to cause this issue:

```
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/hawking.py", line 206, in <module>
    hawking.run()
  File "/usr/local/bin/hawking/code/hawking.py", line 198, in run
    self.bot.run(utilities.load_json(self.token_file_path)["token"])
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/client.py", line 640, in run
    return future.result()
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/client.py", line 499, in connect
    await self._connect()
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/client.py", line 463, in _connect
    await self.ws.poll_event()
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/gateway.py", line 425, in received_message
    func(data)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/state.py", line 750, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/state.py", line 725, in _get_create_guild
    guild._from_data(data)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/guild.py", line 296, in _from_data
    self._sync(guild)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/guild.py", line 323, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```

Fortunately, I'm not the only one to experience this (see: https://github.com/Rapptz/discord.py/issues/5109). The recommended course of action seems to be to update discord.py to the latest version (1.3.4), as it's currently on 1.3.2

**Comment by saiv123** [comment]
was this fixed, i know this was only 2 hours ago

**Comment by naschorr** [comment]
> 
> 
> was this fixed, i know this was only 2 hours ago

Yup, I've just merged it in to master, and updated the deployed version of the bot. Everything should be working fine now.

**Comment by saiv123** [comment]
thanks

**Comment by Tsunami100** [comment]
is there any plan to fix the bug for previous versions? (like v0.16)

**Comment by naschorr** [comment]
@Tsunami100 I doubt it, though I don't see why you couldn't back port the changes to your own repo. The fix itself doesn't seem too wild: https://github.com/Rapptz/discord.py/commit/10d1feb3efd699500f1adb4cee8d965518b0d061#diff-8359e9b5c3ab56e3edee2a02209a7041

**Comment by Tsunami100** [comment]
I fixed it like Pieter-Jan Briers said in [stack](https://stackoverflow.com/questions/63027848/discord-py-glitch-or-random-error-typeerror-new-got-an-unexpected-keywor), changed the channel.py file
