### ISSUE TITLE
Hawking refuses to connect to a voice channel until after rebooting.

### ISSUE THREAD

**Issue by naschorr** [naschorr/hawking#81]
Kudos to the user that reported this in the discord. The bug itself only seems to happen on a per server basis, as Hawking will work fine on another server created by the owners of the affected server. Also, kicking and re-inviting Hawking to the affected server won't fix the issue. It only seems to resolve itself upon reboot.

Here's the relevant redacted logs that should correspond to the issue:
```
2021-03-06 21:00:01,371 - audio_player - audio_player_loop - ERROR - CancelledError during audio_player_loop, ignoring and continuing loop.
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 205, in audio_player_loop
    self.active_play_request = await self.audio_play_queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
2021-03-06 21:00:01,374 - audio_player - audio_player_loop - ERROR - CancelledError during audio_player_loop, ignoring and continuing loop.
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 205, in audio_player_loop
    self.active_play_request = await self.audio_play_queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
2021-03-06 21:00:01,374 - audio_player - audio_player_loop - ERROR - CancelledError during audio_player_loop, ignoring and continuing loop.
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 205, in audio_player_loop
    self.active_play_request = await self.audio_play_queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
2021-03-06 21:00:01,374 - audio_player - audio_player_loop - ERROR - CancelledError during audio_player_loop, ignoring and continuing loop.
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 205, in audio_player_loop
    self.active_play_request = await self.audio_play_queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
2021-03-06 21:00:01,381 - audio_player - audio_player_loop - ERROR - CancelledError during audio_player_loop, ignoring and continuing loop.
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 205, in audio_player_loop
    self.active_play_request = await self.audio_play_queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
2021-03-06 21:00:01,382 - audio_player - audio_player_loop - ERROR - Exception inside audio player event loop
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 218, in audio_player_loop
    voice_client = await self.get_voice_client(self.active_play_request.channel)
  File "/usr/local/bin/hawking/code/audio_player.py", line 141, in get_voice_client
    return await channel.connect()
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/abc.py", line 1101, in connect
    await voice.connect(reconnect=reconnect)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/voice_client.py", line 252, in connect
    await self.ws.poll_event()
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/gateway.py", line 822, in poll_event
    await self.received_message(json.loads(msg.data))
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/gateway.py", line 753, in received_message
    await self.initial_connection(data)
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/gateway.py", line 776, in initial_connection
    recv = await self.loop.sock_recv(state.socket, 70)
concurrent.futures._base.CancelledError
2021-03-06 21:00:01,397 - audio_player - audio_player_loop - DEBUG - Playing file at: /usr/local/bin/hawking/temp/1615033724883.wav, in channel: <REDACTED>, in server: <REDACTED>, for user: <REDACTED>
2021-03-06 21:00:01,397 - audio_player - audio_player_loop - ERROR - Exception inside audio player event loop
Traceback (most recent call last):
  File "/usr/local/bin/hawking/code/audio_player.py", line 278, in audio_player_loop
    voice_client.play(self.active_play_request.audio, after=after_play_callback_builder())
  File "/usr/local/bin/hawking/lib/python3.6/site-packages/discord/voice_client.py", line 402, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
```

**Comment by naschorr** [comment]
Seemingly addressed with #185
